query GET_INVOICE($id: String!) {
  getExternalInvoice(id: $id) {
    data {
      id
      status
      accountName
      seller {
        id
        name
        contact {
          email
        }
      }
      invoiceCreatedDate
      jsonData
      comment
    }
  }
}
