query INVOICES($listInvoicesParams: ListInvoicesParams) {
  listExternalInvoices(listInvoicesParams: $listInvoicesParams) {
    data {
      id
      status
      accountName
      seller {
        id
        name
        contact {
          email
        }
      }
      invoiceCreatedDate
      jsonData
      comment
    }
    pagination {
      page
      pageSize
      total
    }
  }
}
